#!/usr/bin/env perl
use strict;
use warnings;

sub current_branch {
    my @branches = split /\n/, `git branch --no-color 2> /dev/null`;
    my ($branch) = grep { s/^[\*]\s+// } @branches;
    $branch;
}

my $branch = current_branch();
`git push origin $branch`;
