#!/usr/bin/env perl

use strict;
use warnings;
use 5.10.1;

sub current_branch {
    my @branches = split /\n/, `git branch --no-color 2> /dev/null`;
    my ($branch) = grep { s/^[\*]\s+// } @branches;
    $branch;
}

my $branch = current_branch();
if ($branch =~ /iss([0-9]+)/) {
    say `gh pull-request -i $1`;
}

__END__

現在のブランチにiss{nnn}があればそれに紐付けてプルリクする
