#!/usr/bin/env perl
use strict;
use warnings;
use URI;

my @matched = grep { /^origin/ } split "\n", `git remote -v` or die "no origin";
my $uri = URI->new([split /\s/, $matched[0]]->[1]);
my $path = $uri->path;

$path =~ s/\.git$// or die "Can't find path";

`open https://github.com/$path/issues/new`;
